PARALLEL_TYPE: 'ddp'
DATA:
  IMG_SIZE: 512
  DATASET: fetal
  BATCH_SIZE: 16
  AUGM: False
  IMG_SCALING: False
MODEL:
  TYPE: effnetv2
  NAME: effnetv2_classic_l1_no_sigmoid_no_scaling_drop04_abdomen
  NUM_CLASSES: 1
  TASK_TYPE: reg
  AFFIX: .csv
  LABEL_SMOOTHING: 0.0
  LOSS: 'L1'
  DROP_RATE : 0.4
  SIGMOID: False
  BODY_PART: 'abdomen'
TRAIN:
  EPOCHS: 90
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 0.05
  BASE_LR: 6.25e-3
  WARMUP_LR: 6.25e-08
  MIN_LR: 6.25e-07
AUG:
  MIXUP: 0.0
  CUTMIX: 0.0