PARALLEL_TYPE: 'ddp'
DATA:
  IMG_SIZE: 512
  DATASET: fetal
  BATCH_SIZE: 8
  AUGM: False
  IMG_SCALING: True
MODEL:
  TYPE: effnetv2_meta
  NAME: effnetv2_reg_l1_scaling_drop04
  NUM_CLASSES: 1
  TASK_TYPE: reg
  AFFIX: .csv
  LABEL_SMOOTHING: 0.0
  LOSS: 'L1'
  DROP_RATE : 0.4
TRAIN:
  EPOCHS: 90
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 0.05
  BASE_LR: 1.25e-3 # 4096 batch-size
  WARMUP_LR: 1.25e-8
  MIN_LR: 1.25e-6
AUG:
  MIXUP: 0.0
  CUTMIX: 0.0