method: bayes
metric:
  goal: maximize
  name: 'Val Recall'
parameters:
  augm:
    values:
      - false
  attention:
    values:
      - true
  dropout:
    distribution: uniform
    max: 0.3
    min: 0.0
  base_lr:
    distribution: uniform
    max: 5.25e-08
    min: 5.25e-09
  optimizer:
    values:
      - 'adamw'
program: new_main.py
command:
  - srun
  - python3
  - ${program}
  - ${args}