method: bayes
metric:
  goal: minimize
  name: 'Val MAPE'
parameters:
  augm:
    values:
      - true
      - false
  dropout:
    distribution: uniform
    max: 0.4
    min: 0.0
  base_lr:
    distribution: uniform
    max: 5.25e-06
    min: 5.25e-10
  optimizer:
    values:
      - 'adamw'
program: new_main.py
command:
  - srun
  - python3
  - ${program}
  - ${args}
