method: bayes
metric:
  goal: minimize
  name: 'Val MAPE'
parameters:
  augm:
    values:
      - false
  key_frame_attention:
    values:
      - true
  use_head:
    values:
      - false
  use_gelu:
    values:
      - true
  use_skip_connection:
    values:
      - true
  use_batch_norm:
    values:
      - true
  use_alpha:
    values:
      - true
  dropout:
    distribution: uniform
    max: 0.2
    min: 0.0
  base_lr:
    distribution: uniform
    max: 5.25e-05
    min: 5.25e-06
  optimizer:
    values:
      - 'adamw'
program: new_main.py
command:
  - srun
  - python3
  - ${program}
  - ${args}