method: bayes
metric:
  goal: minimize
  name: 'Val MAPE'
parameters:
  augm:
    values:
      - true
      - false
  dropout:
    distribution: uniform
    max: 0.6
    min: 0.1
  base_lr:
    distribution: uniform
    max: 1.25e-05
    min: 1.25e-07
  optimizer:
    values:
      - 'adamw'
      - 'sgd'
      - 'rms'
  scaling:
    values:
      - true
      - false
  attention:
    values:
      - true
      - false
program: new_main.py
command:
  - srun
  - python3
  - ${program}
  - ${args}
