PARALLEL_TYPE: 'ddp'
DATA:
  IMG_SIZE: 512
  DATASET: fetal
  BATCH_SIZE: 8 #per 1 gpu
  AUGM: True
  IMG_SCALING: False
MODEL:
  TYPE: effnetv2
  NAME: effnetv2_cls
  NUM_CLASSES: 7
  TASK_TYPE: cls
  AFFIX: .csv
  LOSS: 'L1'
  DROP_RATE : 0.15
  SIGMOID: False
  ATTENTION: True
  BODY_PART: 'all'

TRAIN:
  EPOCHS: 90
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 0.05
  BASE_LR: 1.25e-6
  WARMUP_LR: 1.25e-6
  MIN_LR: 1.25e-8