PARALLEL_TYPE: 'ddp'
DATA:
  IMG_SIZE: 512
  DATASET: fetal
  BATCH_SIZE: 16 #per 1 gpu
  AUGM: True
  NUM_WORKERS : 4
  IMG_SCALING: False
  VIDEOS_VAL: /data/kpusteln/Fetal-RL/data_preparation/data_biometry/ete_model/biometry_scaled_ps/class_data/biometry_train_all.csv
  VIDEOS_TRAIN: /data/kpusteln/Fetal-RL/data_preparation/data_biometry/ete_model/biometry_scaled_ps/class_data/biometry_train_all.csv
MODEL:
  TYPE: effnetv2
  NAME: effnetv2_bayes_search
  NUM_CLASSES: 7
  TASK_TYPE: cls
  AFFIX: .csv
  LOSS: 'L1'
  DROP_RATE : 0.4
  SIGMOID: False
  ATTENTION: True
  BODY_PART: 'all'
  KEY_FRAME_ATTENTION: False

TRAIN:
  NUM_FRAMES: 3
  EPOCHS: 90
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 0.05
  BASE_LR: 1.25e-5
  WARMUP_LR: 1.25e-9
  MIN_LR: 1.25e-8