PARALLEL_TYPE: 'ddp'
EVAL_MODE: TRUE
DATA:
  IMG_SIZE: 512
  DATASET: fetal
  BATCH_SIZE: 256
  AUGM: False
  TRAIN_SET: '/data/kpusteln/Fetal-RL/data_preparation/data_biometry/ete_model/biometry_scaled_ps/all/biometry_val_scaled_size_all_filtered_for_eval.csv'
  VAL_SET: '/data/kpusteln/Fetal-RL/data_preparation/test_data/results_two_models_cls_filtered.csv'
MODEL:
  TYPE: effnetv2
  NAME: effnetv2_reg
  NUM_CLASSES: 1
  TASK_TYPE: reg
  AFFIX: .csv
TRAIN:
  EPOCHS: 90
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 0.05
  BASE_LR: 1.25e-3 # 4096 batch-size
  WARMUP_LR: 1.25e-7
  MIN_LR: 1.25e-6
  AUTO_RESUME: FALSE
  OPTIMIZER:
      NAME: adamW