PARALLEL_TYPE: 'ddp'
DATA:
  IMG_SIZE: 512
  DATASET: fetal
  BATCH_SIZE: 16
  AUGM: True
  IMG_SCALING: False
MODEL:
  TYPE: effnetv2
  NAME: effnetv2_bayes_search
  NUM_CLASSES: 1
  TASK_TYPE: reg
  AFFIX: .csv
  LOSS: 'L1'
  DROP_RATE : 0.4
  SIGMOID: False
  ATTENTION: True
  BODY_PART: 'all'

TRAIN:
  EPOCHS: 90
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 0.05
  BASE_LR: 1.25e-5
  WARMUP_LR: 1.25e-10
  MIN_LR: 1.25e-8