PARALLEL_TYPE: 'ddp'
DATA:
  IMG_SIZE: 512
  DATASET: fetal
  BATCH_SIZE: 4 #per 1 gpu
  AUGM: False
  IMG_SCALING: False
  VIDEOS_VAL: /data/kpusteln/Fetal-RL/data_preparation/data_biometry/ete_model/biometry_scaled_ps/all/videos_val.csv
  VIDEOS_TRAIN: /data/kpusteln/Fetal-RL/data_preparation/data_biometry/ete_model/biometry_scaled_ps/all/videos_train.csv
MODEL:
  TYPE: swin-video
  NAME: swin-video_bayes_search
  NUM_CLASSES: 1
  TASK_TYPE: reg
  AFFIX: .csv
  LOSS: 'L1'
  DROP_RATE : 0.4
  SIGMOID: False
  ATTENTION: True
  BODY_PART: 'all'
  KEY_FRAME_ATTENTION: True

TRAIN:
  NUM_FRAMES: 3
  EPOCHS: 1200
  WARMUP_EPOCHS: 66
  WEIGHT_DECAY: 0.05
  BASE_LR: 1.25e-5
  WARMUP_LR: 1.25e-8
  MIN_LR: 1.25e-8